INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (1,110,26,"This is too hard!",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (2,110,26,"Nothing is happening.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (3,105,26,"I feel a bit better.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (4,105,25,"I need a beer.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (5,104,25,"At least I made it this far.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (6,104,25,"No shame in quitting now?",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (7,104,25,"Maybe I can have chocolate now.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (8,104,24.5,"This is too hard!",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (9,102,24.5,"This is too hard!",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (10,102,24.5,"Stupid app.  I hate you but I must defeat you.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (11,102,24,"This is not so bad.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (12,102,24,"Not so tired today.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (13,102,24,"This is too hard!",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (14,101,24,"Hmm ok.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (15,101,24,"Hmm ok.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (16,101,23.4,"This is too hard!",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (17,101,23.4,"This is too hard!",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (18,100,23.4,"I can do this.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (19,100,23.4,"Feeling more upbeat.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (20,100,22,"Not so winded anymore.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (21,100,22,"OMG make this end.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (22,100,22,"OMG make this end.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (23,99,22,"OMG make this end.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (24,99,21.8,"So close to being done.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (25,99,21.8,"So close to being done.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (26,99,21.8,"I am going to celebrate with cake.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (27,98,21.8,"Feeling more optimistic.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (28,98,21,"Can finally join that gym.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (29,98,21,"One more day.",NOW(),NOW());
INSERT INTO metrics (day_id,rbpm,bmi,blog,createdAt,updatedAt) VALUES (30,98,21,"I did it!",NOW(),NOW());